services:
  - type: web
    name: viuda-negra
    env: php
    buildCommand: echo "No build needed for PHP"
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PHP_VERSION
        value: 8.1
